version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::950031890817:user/aws-sam-cli-managed-dev-env-pipeline-PipelineUser-1TWXHULKMARJG"

[dev_env]
[dev_env.pipeline_bootstrap]
[dev_env.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::950031890817:role/aws-sam-cli-managed-dev-env-PipelineExecutionRole-18PSB0XOADM4O"
cloudformation_execution_role = "arn:aws:iam::950031890817:role/aws-sam-cli-managed-dev-e-CloudFormationExecutionR-1DT44CBI591RB"
artifacts_bucket = "aws-sam-cli-managed-dev-env-pipel-artifactsbucket-1wl9wpphy3a40"
image_repository = ""
region = "us-east-1"

[prod_env]
[prod_env.pipeline_bootstrap]
[prod_env.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::950031890817:role/aws-sam-cli-managed-prod-env-PipelineExecutionRole-11POZU9WA1IRP"
cloudformation_execution_role = "arn:aws:iam::950031890817:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-3DY7BPT0WEBR"
artifacts_bucket = "aws-sam-cli-managed-prod-env-pipe-artifactsbucket-oeb7qw10icoe"
image_repository = ""
region = "us-east-1"
